<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Grr</name>
   <tag></tag>
   <elementGuidId>23bac905-c634-4580-a820-a00f38efc5c1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_39n</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalContainer&quot;)/div[@class=&quot;_1oxj uiLayer&quot;]/div[@class=&quot;_49v- _22uo&quot;]/div[@class=&quot;_1oxk&quot;]/div[@class=&quot;_iu- _628b _1ef3&quot;]/span[@class=&quot;_iuw _iuy&quot;]/div[@class=&quot;_39m _1ef2&quot;]/div[@class=&quot;_39n&quot;]</value>
   </webElementProperties>
</WebElementEntity>
