<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_piclink</name>
   <tag></tag>
   <elementGuidId>f6f4d5d2-4739-4793-842f-87670c612d7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body.js-focus-visible:nth-child(12) div.container.users-list-container:nth-child(2) div.col-md-8 div.tab-content div.tab-pane.active ul.user-list.clearfix genericlist.clearfix ul.user-list.clearfix div.aspect-ratio li.user-list-person:nth-child(2) profilepreview:nth-child(1) div.aspect-ratio div.main-link.content > a.piclink:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/app[1]/maincomp[1]/main[1]/home[1]/div[2]/div[1]/div[2]/div[1]/div[1]/ul[1]/homefeatured[1]/genericlist[1]/listview[1]/ul[1]/div[1]/li[1]/profilepreview[1]/div[1]/div[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>piclink</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/main/profile/623655</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;featured&quot;)/ul[@class=&quot;user-list clearfix&quot;]/homefeatured[1]/genericlist[@class=&quot;clearfix&quot;]/listview[1]/ul[@class=&quot;user-list clearfix&quot;]/div[@class=&quot;aspect-ratio&quot;]/li[@class=&quot;user-list-person&quot;]/profilepreview[1]/div[@class=&quot;aspect-ratio&quot;]/div[@class=&quot;main-link content&quot;]/a[@class=&quot;piclink&quot;]</value>
   </webElementProperties>
</WebElementEntity>
