<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Curtir</name>
   <tag></tag>
   <elementGuidId>1201afb9-d8b2-49b1-a3cb-f3afd3029133</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>UFILikeLink _4x9- _4x9_ _48-k</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>fb-ufi-likelink</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Curtir</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_36_e&quot;)/div[@class=&quot;_sa_ _gsd _fgm _5vsi _192z _1sz4 _1i6z&quot;]/div[@class=&quot;_37uu&quot;]/div[1]/div[@class=&quot;_57w&quot;]/div[@class=&quot;_3399 _a7s _20h6 _610i _610j _125r _2h27 clearfix _zw3&quot;]/div[@class=&quot;_524d&quot;]/div[@class=&quot;_42nr _1mtp&quot;]/span[@class=&quot;_1mto&quot;]/div[@class=&quot;_khz _4sz1 _4rw5 _3wv2&quot;]/a[@class=&quot;UFILikeLink _4x9- _4x9_ _48-k&quot;]</value>
   </webElementProperties>
</WebElementEntity>
