<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Fechar</name>
   <tag></tag>
   <elementGuidId>9cafbd43-fa29-42fc-bdb5-50e94e806dc4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_51-t _50zy _50-0 _50z- _5upp _42ft</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Fechar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fechar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;facebook&quot;)/body[@class=&quot;_4lh timelineLayout _51x9 noFooter fbx hasBanner _-kb _61s0 _605a b_1ggrx7fafh chrome webkit win x1 Locale_pt_BR&quot;]/div[@class=&quot;_10 _51ly uiLayer _4-hy _3qw&quot;]/div[@class=&quot;_59s7&quot;]/div[@class=&quot;_4t2a&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;_4-i0&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;_ohf rfloat&quot;]/div[@class=&quot;_51-u&quot;]/button[@class=&quot;_51-t _50zy _50-0 _50z- _5upp _42ft&quot;]</value>
   </webElementProperties>
</WebElementEntity>
