<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Renatinhaaaa1</name>
   <tag></tag>
   <elementGuidId>0c0d77b6-7847-4f5a-b0d6-b5f67a94e747</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Renatinhaaaa1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igaveaccess&quot;)/ul[@class=&quot;mini-users-list&quot;]/li[1]/profilepreviewsmall[1]/a[@class=&quot;clearfix&quot;]/div[@class=&quot;info&quot;]/p[@class=&quot;username&quot;]</value>
   </webElementProperties>
</WebElementEntity>
