<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_BloquearDenunciar</name>
   <tag></tag>
   <elementGuidId>42f125e8-cd7b-4495-8b7e-5021bd71cdb1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>dropdownprofile</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BloquearDenunciar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;js-focus-visible&quot;]/app[1]/maincomp[1]/main[1]/profilepage[1]/main[1]/div[@class=&quot;container profile-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-lg-8 profile-big-col&quot;]/div[1]/div[@class=&quot;basic-info row flex&quot;]/div[@class=&quot;menu-col&quot;]/div[@class=&quot;col-xs-5 col-md-12&quot;]/div[@class=&quot;user-options-menu&quot;]/div[@class=&quot;dropdown-container&quot;]/div[@class=&quot;dropdown visible-md visible-lg open&quot;]/ul[@class=&quot;dropdown-menu&quot;]</value>
   </webElementProperties>
</WebElementEntity>
